# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017 #computadora:contenedor
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
